# Generated by Django 3.1.2 on 2020-10-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('category', models.CharField(default='', max_length=100)),
                ('sub_category', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='shop/pro_image')),
                ('product_desc', models.TextField()),
                ('published_date', models.DateField()),
            ],
        ),
    ]
